name: Build/release

on:
  push:
    # branches:
    #   - main
    tags:
      - '*'

jobs:
  start_notify:
    runs-on: ubuntu-20.04
    steps:
      - name: notify with bark
        run: curl -v "https://api.day.app/${{ secrets.barkid }}/third action-${GITHUB_REF##*/}\[$GITHUB_RUN_ID\] 开始/点击跳转到action页面?url=https://github.com/Erriy/third/actions/runs/$GITHUB_RUN_ID"

  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - name: Install bsdtar
        if: matrix.os == 'ubuntu-20.04'
        run: sudo apt-get install -y libarchive-tools

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 10
          registry-url: 'https://registry.npmjs.com'

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
  finish_notify:
    if: always()
    needs: release
    runs-on: ubuntu-20.04
    steps:
      - name: notify with bark
        run: curl -v "https://api.day.app/${{ secrets.barkid }}/third action-${GITHUB_REF##*/}\[$GITHUB_RUN_ID\] 结束/点击跳转到releases页面?url=https://github.com/Erriy/third/releases"
